# Generated by Django 5.0.1 on 2025-02-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_doctor_password_doctor_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('symptoms', models.TextField()),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('opticket_number', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Admin.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Admin.user')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('disease_identified', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('medicines', models.TextField(help_text='List of prescribed medicines')),
                ('consultation_date', models.DateTimeField(auto_now_add=True)),
                ('patient_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Admin.patientbooking')),
            ],
        ),
    ]
