# Generated by Django 5.1 on 2025-03-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0004_patientbooking_consultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deviceid",
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
    ]
