# Generated by Django 5.1 on 2025-03-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0005_user_deviceid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="deviceid",
            field=models.CharField(max_length=550, null=True),
        ),
    ]
