# Generated by Django 5.1 on 2025-03-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0006_alter_user_deviceid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
