# Generated by Django 5.1 on 2025-03-16 04:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0007_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientbooking",
            name="time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="DailyHealthData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("systolic_bp", models.IntegerField(blank=True, null=True)),
                ("diastolic_bp", models.IntegerField(blank=True, null=True)),
                ("pulse", models.IntegerField(blank=True, null=True)),
                ("blood_sugar_fasting", models.FloatField(blank=True, null=True)),
                ("blood_sugar_post_meal", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=150, unique=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.user"
                    ),
                ),
            ],
        ),
    ]
