# Generated by Django 5.1 on 2025-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0008_patientbooking_time_dailyhealthdata_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientbooking",
            name="ConsltNumber",
            field=models.IntegerField(default=0),
        ),
    ]
