# Generated by Django 5.1 on 2025-03-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0009_patientbooking_consltnumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("status", models.IntegerField(default=1)),
                ("ConsltNumber", models.IntegerField(default=0)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.doctor"
                    ),
                ),
            ],
        ),
    ]
